import pytest
from miorom.core import SymbolMap, SymbolEntry


def test_symbol_map_basic():
    smap = SymbolMap()
    smap.add(0x02000000, "main", size=0x100, kind="code", comment="Main loop")
    smap.add(0x02000100, "str_table", size=0x200, kind="data", comment="String table")

    assert len(smap) == 2
    assert "main" in smap
    assert 0x02000000 in smap
    assert smap["main"] == 0x02000000
    assert smap[0x02000000] == 0x02000000

    entry = smap.resolve("main")
    assert isinstance(entry, SymbolEntry)
    assert entry.name == "main"
    assert entry.comment == "Main loop"

    with pytest.raises(KeyError):
        _ = smap["unknown_symbol"]


def test_symbol_map_export_sym():
    smap = SymbolMap()
    smap.add(0x02001000, "fn_dialogue", comment="Dialogue entrypoint")
    exported = smap.export_sym_file()

    assert "; Generated by MioROM SymbolMap" in exported
    assert "02001000 fn_dialogue ; Dialogue entrypoint" in exported


def test_symbol_map_export_csv():
    smap = SymbolMap()
    smap.add(0x02001000, "fn_dialogue", size=0x40, kind="code", comment="Dialogue entry")
    csv_out = smap.export_csv()

    assert "Name,Address,Size,Type,Comment" in csv_out
    assert '"fn_dialogue",0x02001000,64,"code","Dialogue entry"' in csv_out


def test_symbol_map_import_sym():
    sym_content = """
    ; This is a comment
    # Another comment
    02001000 fn_init ; initialize
    02002000 data_items
    invalid line
    """
    smap = SymbolMap()
    count = smap.import_sym_text(sym_content)
    assert count == 2
    assert smap["fn_init"] == 0x02001000
    assert smap["data_items"] == 0x02002000
