import struct
import pytest
from miorom.script.engine import BytecodeEngine
from miorom.script.opcode import ArgString, ArgU16
from miorom.script.repacker import SmartScriptRepacker, ScriptRepackReport
from miorom.text.po_handler import PoHandler


def test_smart_script_repacker_arbitrary_lengthening():
    engine = BytecodeEngine(endian="<")
    engine.register_opcode(0x01, "NOP")
    engine.register_opcode(0x02, "TEXT", [ArgString("dialogue")])
    engine.register_opcode(0x03, "JUMP", [ArgU16("target", is_jump_target=True)])
    engine.register_opcode(0xFF, "EXIT")

    # Construct initial script:
    # 0x00: TEXT "Hi" (1 + 2 + 1 null = 4 bytes: [0x02, 'H', 'i', 0x00])
    # 0x04: JUMP 0x0A (1 + 2 = 3 bytes: [0x03, 0x0A, 0x00])
    # 0x07: NOP (1 byte: [0x01])
    # 0x08: NOP (1 byte: [0x01])
    # 0x09: NOP (1 byte: [0x01])
    # 0x0A: TEXT "End" (4 bytes: [0x02, 'E', 'n', 'd', 0x00]) -> 5 bytes total: offset 0x0A..0x0E
    # 0x0F: EXIT (1 byte: [0xFF])
    initial_script = bytearray()
    initial_script.extend(b"\x02Hi\x00")              # 0x00..0x03
    initial_script.extend(b"\x03\x09\x00")          # 0x04..0x06 (jump to 0x09)
    initial_script.extend(b"\x01\x01")              # 0x07..0x08 (2 NOPs)
    initial_script.extend(b"\x02End\x00")           # 0x09..0x0D (TEXT "End")
    initial_script.extend(b"\xFF")                  # 0x0E (EXIT)

    repacker = SmartScriptRepacker(engine)
    disasm_script, po_handler = repacker.unpack_to_po(
        script_data=bytes(initial_script),
        external_entry_points=[0x00, 0x09],
    )

    assert len(po_handler.entries) == 2
    assert po_handler.entries[0].msgid == "Hi"
    assert po_handler.entries[1].msgid == "End"

    # Lengthen text dramatically (from 2 characters to 50+ characters)
    po_handler.entries[0].msgstr = "Halo semua kawan-kawan sekalian yang berbahagia dan ceria!"
    po_handler.entries[1].msgstr = "Tamat permainan cerita petualangan ini sekarang."

    new_bytecode, report = repacker.repack_with_translations(
        script=disasm_script,
        po_source=po_handler,
        external_entry_points=[0x00, 0x09],
    )

    # Verify expansion and size
    assert report.total_strings_updated == 2
    assert report.new_size > len(initial_script)
    assert report.size_delta > 0

    # Verify external entry point for "End" (originally at 0x09) shifted forward
    assert 0x09 in report.external_pointers_updated
    new_end_offset = report.external_pointers_updated[0x09]
    assert new_end_offset > 0x09

    # Disassemble newly generated bytecode to verify Jump target points to new_end_offset
    new_disasm = engine.disassemble(new_bytecode)
    jump_ins = next(ins for ins in new_disasm.instructions if ins.name == "JUMP")
    assert jump_ins.args["target"] == f"LABEL_{new_end_offset:04X}" or jump_ins.args["target"] == new_end_offset
