from miorom.core.binary import BinaryReader, BinaryWriter
from miorom.core.bitstream import BitReader, BitWriter
from miorom.core.bits import (
    rol,
    ror,
    bit_reverse,
    bit_reverse8,
    bit_reverse16,
    bit_reverse32,
    swap_nibbles,
    pack_nibbles,
    unpack_nibbles,
    sign_extend,
    popcount,
    clz,
    ctz,
    bswap16,
    bswap32,
    bswap64,
)
from miorom.core.huffman_tree import (
    HuffmanNode,
    build_huffman_tree,
    extract_code_lengths,
    generate_canonical_codes,
    CanonicalHuffmanTable,
)
from miorom.core.bus_mapper import SNESBusMapper, NESBusMapper, GameBoyBusMapper
from miorom.core.checksum import RetroChecksum
from miorom.core.slicer import (
    align_up,
    align_down,
    pad_bytes,
    chunk_bytes,
    find_free_blocks,
    BinarySlicer,
)
from miorom.core.ring_buffer import RingBuffer, LzssMatchFinder
from miorom.core.entropy import (
    calculate_entropy,
    byte_frequency,
    sliding_entropy_scan,
    chi_squared_test,
    find_entropy_regions,
)
from miorom.core.cipher import (
    xor_bytes,
    rolling_xor,
    invert_bytes,
    add_cipher,
    crack_single_byte_xor,
)
from miorom.core.interleave import (
    combine_split_words,
    split_words,
    deinterleave_channels,
    interleave_channels,
)
from miorom.core.delta import (
    cumulative_offsets,
    offsets_to_lengths,
    delta_decode,
    delta_encode,
    relative_to_absolute,
    absolute_to_relative,
)
from miorom.core.pointer_analyzer import (
    PointerSequenceMetrics,
    PointerTableCandidate,
    unpack_pointer,
    pack_pointer,
    unpack_pointers,
    pack_pointers,
    verify_stride_monotonicity,
    calculate_monotonicity_ratio,
    analyze_pointer_sequence,
    remap_pointers,
    find_pointer_tables,
)
from miorom.core.far_pointer import (
    BankedPointer,
    SplitPointerTable,
    InterleavedPointerTable,
    resolve_banked_to_offset,
    resolve_offset_to_banked,
    read_split_pointer_table,
    write_split_pointer_table,
    read_interleaved_pointer_table,
    write_interleaved_pointer_table,
    relocate_banked_table,
)
from miorom.core.pointer import PointerTable, PointerEntry, SegmentTable, SegmentedAddressResolver
from miorom.core.scanner import (
    FoundString,
    TextBlock,
    CandidatePointerTable,
    StringScanner,
    PointerScanner,
)
from miorom.core.mapper import ByteOffsetMapper
from miorom.core.buffer import RelocatableBuffer
from miorom.core.memory import MemoryMap, MemoryRegion
from miorom.core.signatures import SignaturePattern, SignatureScanner
from miorom.core.bank_expander import RomExpander, FarPointerRelocator, AllocatedItem
from miorom.core.schema import (
    BinaryStruct,
    SchemaField,
    U8,
    I8,
    U16,
    I16,
    U32,
    I32,
    U64,
    Float32,
    FixedString,
    RawBytes,
    Array,
    EnumField,
    Bitfield,
    BitfieldView,
    If,
    Padding,
    Alignment,
    Computed,
    PascalString,
    SentinelArray,
    ChecksumField,
)

from miorom.core.multilevel_pointer import MultiLevelPointerTable, TableLevel
from miorom.core.integrity import IntegrityReport, RomIntegrityManager
from miorom.core.struct_profiler import (
    StructProfiler,
    StructProfile,
    FieldProfile,
    FieldType,
    StrideCandidate,
)
from miorom.core.overlay_mapper import (
    MemoryOverlayMapper,
    OverlayRegion,
    DMACopyRecord,
)
from miorom.core.heap_builder import StringHeapBuilder, HeapBuildResult
from miorom.core.vlq import (
    VariableLengthIntCodec,
    encode_vlq,
    decode_vlq,
    encode_uleb128,
    decode_uleb128,
    encode_sleb128,
    decode_sleb128,
)
from miorom.core.string_carver import StringPoolCarver, CarvedString
from miorom.core.record_builder import RecordBuilder
from miorom.core.symbol_map import SymbolMap, SymbolEntry
from miorom.core.hex_diff import HexDiffHighlighter
from miorom.core.cstruct import CStructOverlay, CStructInstance, CField
from miorom.core.bitfield import BitField, BitFieldSchema, BitFieldCodec

__all__ = [
    "BinaryReader",
    "BinaryWriter",
    "BitReader",
    "BitWriter",
    "rol",
    "ror",
    "bit_reverse",
    "bit_reverse8",
    "bit_reverse16",
    "bit_reverse32",
    "swap_nibbles",
    "pack_nibbles",
    "unpack_nibbles",
    "sign_extend",
    "popcount",
    "clz",
    "ctz",
    "bswap16",
    "bswap32",
    "bswap64",
    "HuffmanNode",
    "build_huffman_tree",
    "extract_code_lengths",
    "generate_canonical_codes",
    "CanonicalHuffmanTable",
    "SNESBusMapper",
    "NESBusMapper",
    "GameBoyBusMapper",
    "RetroChecksum",
    "align_up",
    "align_down",
    "pad_bytes",
    "chunk_bytes",
    "find_free_blocks",
    "BinarySlicer",
    "RingBuffer",
    "LzssMatchFinder",
    "calculate_entropy",
    "byte_frequency",
    "sliding_entropy_scan",
    "chi_squared_test",
    "find_entropy_regions",
    "xor_bytes",
    "rolling_xor",
    "invert_bytes",
    "add_cipher",
    "crack_single_byte_xor",
    "combine_split_words",
    "split_words",
    "deinterleave_channels",
    "interleave_channels",
    "cumulative_offsets",
    "offsets_to_lengths",
    "delta_decode",
    "delta_encode",
    "relative_to_absolute",
    "absolute_to_relative",
    "PointerSequenceMetrics",
    "PointerTableCandidate",
    "unpack_pointer",
    "pack_pointer",
    "unpack_pointers",
    "pack_pointers",
    "verify_stride_monotonicity",
    "calculate_monotonicity_ratio",
    "analyze_pointer_sequence",
    "remap_pointers",
    "find_pointer_tables",
    "BankedPointer",
    "SplitPointerTable",
    "InterleavedPointerTable",
    "resolve_banked_to_offset",
    "resolve_offset_to_banked",
    "read_split_pointer_table",
    "write_split_pointer_table",
    "read_interleaved_pointer_table",
    "write_interleaved_pointer_table",
    "relocate_banked_table",
    "PointerTable",
    "PointerEntry",
    "SegmentTable",
    "SegmentedAddressResolver",
    "FoundString",
    "TextBlock",
    "CandidatePointerTable",
    "StringScanner",
    "PointerScanner",
    "ByteOffsetMapper",
    "RelocatableBuffer",
    "MemoryMap",
    "MemoryRegion",
    "SignaturePattern",
    "SignatureScanner",
    "RomExpander",
    "FarPointerRelocator",
    "AllocatedItem",
    "BinaryStruct",
    "SchemaField",
    "U8",
    "I8",
    "U16",
    "I16",
    "U32",
    "I32",
    "U64",
    "Float32",
    "FixedString",
    "RawBytes",
    "Array",
    "EnumField",
    "Bitfield",
    "BitfieldView",
    "If",
    "Padding",
    "Alignment",
    "Computed",
    "PascalString",
    "SentinelArray",
    "ChecksumField",
    "MultiLevelPointerTable",
    "TableLevel",
    "IntegrityReport",
    "RomIntegrityManager",
    "StructProfiler",
    "StructProfile",
    "FieldProfile",
    "FieldType",
    "StrideCandidate",
    "MemoryOverlayMapper",
    "OverlayRegion",
    "DMACopyRecord",
    "StringHeapBuilder",
    "HeapBuildResult",
    "VariableLengthIntCodec",
    "encode_vlq",
    "decode_vlq",
    "encode_uleb128",
    "decode_uleb128",
    "encode_sleb128",
    "decode_sleb128",
    "StringPoolCarver",
    "CarvedString",
    "RecordBuilder",
    "SymbolMap",
    "SymbolEntry",
    "HexDiffHighlighter",
    "CStructOverlay",
    "CStructInstance",
    "CField",
    "BitField",
    "BitFieldSchema",
    "BitFieldCodec",
]
