"""
miorom.core.symbol_map
~~~~~~~~~~~~~~~~~~~~~~
Symbol Map & Address Annotator Notebook Primitive.
Provides a structured notebook for reverse engineers to register addresses,
function labels, and table locations, with export support for No$GBA (.sym),
Dolphin (.map), and Ghidra CSV labels.
"""

from miorom.result import MioRomResult
from dataclasses import dataclass, field
from typing import Dict, Iterator, List, Optional, Union

import csv as _csv


@dataclass
class SymbolEntry(MioRomResult):
    """Represents an annotated memory symbol."""
    address: int
    name: str
    size: int = 0
    kind: str = "code"  # "code", "data", "table", "string"
    comment: str = ""


class SymbolMap:
    """
    Reverse engineering address notebook and symbol table.
    """

    def __init__(self):
        self._addr_to_sym: Dict[int, SymbolEntry] = {}
        self._name_to_sym: Dict[str, SymbolEntry] = {}

    def add(
        self,
        address: int,
        name: str,
        size: int = 0,
        kind: str = "code",
        comment: str = "",
    ) -> "SymbolMap":
        """Registers a symbol in the map."""
        sym = SymbolEntry(
            address=address,
            name=name,
            size=size,
            kind=kind,
            comment=comment,
        )
        self._addr_to_sym[address] = sym
        self._name_to_sym[name] = sym
        return self

    def resolve(self, key: Union[int, str]) -> Optional[SymbolEntry]:
        """Resolves by address integer or symbol name string."""
        if isinstance(key, int):
            return self._addr_to_sym.get(key)
        return self._name_to_sym.get(key)

    def __getitem__(self, key: Union[int, str]) -> int:
        """Returns address for name, or raises KeyError."""
        if isinstance(key, str):
            sym = self._name_to_sym.get(key)
            if sym is None:
                raise KeyError(f"Symbol not found: {key}")
            return sym.address
        elif isinstance(key, int):
            sym = self._addr_to_sym.get(key)
            if sym is None:
                raise KeyError(f"Address not mapped: 0x{key:08X}")
            return sym.address
        raise TypeError("Key must be int or str")

    def __contains__(self, key: Union[int, str]) -> bool:
        if isinstance(key, int):
            return key in self._addr_to_sym
        return key in self._name_to_sym

    def __len__(self) -> int:
        return len(self._addr_to_sym)

    def __iter__(self) -> Iterator[SymbolEntry]:
        return iter(sorted(self._addr_to_sym.values(), key=lambda s: s.address))

    def export_sym_file(self) -> str:
        """
        Exports symbols in standard No$GBA / emulator .sym format:
        0201A540 fn_render_dialogue
        """
        lines: List[str] = ["; Generated by MioROM SymbolMap"]
        for sym in self:
            comment_str = f" ; {sym.comment}" if sym.comment else ""
            lines.append(f"{sym.address:08X} {sym.name}{comment_str}")
        return "\n".join(lines)

    def export_csv(self) -> str:
        """
        Exports symbols in Ghidra importable CSV format (Name, Address, Size, Comment).
        """
        lines: List[str] = ["Name,Address,Size,Type,Comment"]
        for sym in self:
            lines.append(f'"{sym.name}",0x{sym.address:08X},{sym.size},"{sym.kind}","{sym.comment}"')
        return "\n".join(lines)

    def import_sym_text(self, text: str) -> int:
        """
        Parses standard .sym text into this map. Returns count of imported symbols.
        Accepts optional trailing size field (``08000100 fn_a 0x40``).
        """
        imported = 0
        for line in text.splitlines():
            clean = line.strip()
            if not clean or clean.startswith(";") or clean.startswith("#"):
                continue
            # Remove inline comments
            if ";" in clean:
                clean = clean.split(";")[0].strip()

            parts = clean.split()
            if len(parts) >= 2:
                try:
                    addr = int(parts[0], 16)
                    name = parts[1]
                    size = int(parts[2], 16) if len(parts) >= 3 else 0
                    self.add(addr, name, size=size)
                    imported += 1
                except ValueError:
                    pass
        return imported

    def import_dolphin_map(self, text: str) -> int:
        """
        Parses a Dolphin emulator ``.map`` file (Wii/GC symbol map).

        Skips section headers (``.text:0x...``) and comments; accepts the
        ``Name|addr=0x...|size=0x...|ver=...`` pipe rows and the older
        ``address size name`` space-separated rows. Returns imported count.
        """
        imported = 0
        for line in text.splitlines():
            clean = line.strip()
            if not clean or clean.startswith("//") or clean.startswith("#"):
                continue
            if ":" in clean and "|" not in clean:
                # Section header like ".text:0x80003100"
                continue

            if "|" in clean:
                parts = [p.strip() for p in clean.split("|")]
                name = parts[0]
                fields: Dict[str, str] = {}
                for kv in parts[1:]:
                    if "=" in kv:
                        k, _, v = kv.partition("=")
                        fields[k.strip()] = v.strip()
                addr = fields.get("addr")
                if addr is None or not name:
                    continue
                try:
                    address = int(addr, 16)
                    size = int(fields.get("size", "0"), 16)
                except ValueError:
                    continue
                self.add(address, name, size=size)
                imported += 1
            else:
                # Legacy format: "address size name"
                parts = clean.split()
                if len(parts) >= 3:
                    try:
                        address = int(parts[0], 16)
                        size = int(parts[1], 16)
                        name = parts[2]
                        self.add(address, name, size=size)
                        imported += 1
                    except ValueError:
                        continue
        return imported

    def import_csv(self, text: str) -> int:
        """
        Parses the CSV produced by :meth:`export_csv` (Ghidra-compatible format).
        Header row and malformed rows are skipped. Returns imported count.
        """
        imported = 0
        for line in text.splitlines():
            clean = line.strip()
            if not clean or clean.startswith("Name,"):
                continue
            rows = next(iter(_csv.reader([clean])))
            if len(rows) < 2:
                continue
            try:
                name = rows[0].strip('"')
                address = int(rows[1].strip().rstrip(","), 16)
                size = int(rows[2]) if len(rows) >= 3 and rows[2].strip() else 0
            except (ValueError, IndexError):
                continue
            kind = rows[3].strip('"') if len(rows) >= 4 else "code"
            comment = rows[4].strip('"') if len(rows) >= 5 else ""
            self.add(address, name, size=size, kind=kind, comment=comment)
            imported += 1
        return imported

    def to_ghidra_script(self) -> str:
        """
        Exports symbols as a standalone Python script runnable directly inside Ghidra's Script Manager.
        """
        lines = [
            "# Ghidra Python Script auto-generated by MioROM",
            "# @category Symbols",
            "from ghidra.program.model.symbol.SourceType import USER_DEFINED",
            "",
            "sym_table = currentProgram.getSymbolTable()",
        ]
        for s in self:
            lines.append(f"sym_table.createLabel(toAddr(0x{s.address:08X}), '{s.name}', USER_DEFINED)")
        return "\n".join(lines)

    def to_ida_idc(self) -> str:
        """
        Exports symbols as an IDA Pro IDC script.
        """
        lines = [
            "#include <idc.idc>",
            "static main() {",
        ]
        for s in self:
            lines.append(f'    set_name(0x{s.address:08X}, "{s.name}", SN_CHECK);')
        lines.append("}")
        return "\n".join(lines)

    def to_sym(self) -> str:
        """
        Exports symbols as a standard No$GBA / PCSX .sym format file.
        """
        lines = ["; No$GBA / Emulator SYM format auto-generated by MioROM"]
        for s in self:
            lines.append(f"{s.address:08X} {s.name}")
        return "\n".join(lines)
