"""
miorom.core.symbol_map
~~~~~~~~~~~~~~~~~~~~~~
Symbol Map & Address Annotator Notebook Primitive.
Provides a structured notebook for reverse engineers to register addresses,
function labels, and table locations, with export support for No$GBA (.sym),
Dolphin (.map), and Ghidra CSV labels.
"""

from dataclasses import dataclass, field
from typing import Dict, Iterator, List, Optional, Union


@dataclass
class SymbolEntry:
    """Represents an annotated memory symbol."""
    address: int
    name: str
    size: int = 0
    kind: str = "code"  # "code", "data", "table", "string"
    comment: str = ""


class SymbolMap:
    """
    Reverse engineering address notebook and symbol table.
    """

    def __init__(self):
        self._addr_to_sym: Dict[int, SymbolEntry] = {}
        self._name_to_sym: Dict[str, SymbolEntry] = {}

    def add(
        self,
        address: int,
        name: str,
        size: int = 0,
        kind: str = "code",
        comment: str = "",
    ) -> "SymbolMap":
        """Registers a symbol in the map."""
        sym = SymbolEntry(
            address=address,
            name=name,
            size=size,
            kind=kind,
            comment=comment,
        )
        self._addr_to_sym[address] = sym
        self._name_to_sym[name] = sym
        return self

    def resolve(self, key: Union[int, str]) -> Optional[SymbolEntry]:
        """Resolves by address integer or symbol name string."""
        if isinstance(key, int):
            return self._addr_to_sym.get(key)
        return self._name_to_sym.get(key)

    def __getitem__(self, key: Union[int, str]) -> int:
        """Returns address for name, or raises KeyError."""
        if isinstance(key, str):
            sym = self._name_to_sym.get(key)
            if sym is None:
                raise KeyError(f"Symbol not found: {key}")
            return sym.address
        elif isinstance(key, int):
            sym = self._addr_to_sym.get(key)
            if sym is None:
                raise KeyError(f"Address not mapped: 0x{key:08X}")
            return sym.address
        raise TypeError("Key must be int or str")

    def __contains__(self, key: Union[int, str]) -> bool:
        if isinstance(key, int):
            return key in self._addr_to_sym
        return key in self._name_to_sym

    def __len__(self) -> int:
        return len(self._addr_to_sym)

    def __iter__(self) -> Iterator[SymbolEntry]:
        return iter(sorted(self._addr_to_sym.values(), key=lambda s: s.address))

    def export_sym_file(self) -> str:
        """
        Exports symbols in standard No$GBA / emulator .sym format:
        0201A540 fn_render_dialogue
        """
        lines: List[str] = ["; Generated by MioROM SymbolMap"]
        for sym in self:
            comment_str = f" ; {sym.comment}" if sym.comment else ""
            lines.append(f"{sym.address:08X} {sym.name}{comment_str}")
        return "\n".join(lines)

    def export_csv(self) -> str:
        """
        Exports symbols in Ghidra importable CSV format (Name, Address, Size, Comment).
        """
        lines: List[str] = ["Name,Address,Size,Type,Comment"]
        for sym in self:
            lines.append(f'"{sym.name}",0x{sym.address:08X},{sym.size},"{sym.kind}","{sym.comment}"')
        return "\n".join(lines)

    def import_sym_text(self, text: str) -> int:
        """
        Parses standard .sym text into this map. Returns count of imported symbols.
        """
        imported = 0
        for line in text.splitlines():
            clean = line.strip()
            if not clean or clean.startswith(";") or clean.startswith("#"):
                continue
            # Remove inline comments
            if ";" in clean:
                clean = clean.split(";")[0].strip()

            parts = clean.split()
            if len(parts) >= 2:
                try:
                    addr = int(parts[0], 16)
                    name = parts[1]
                    self.add(addr, name)
                    imported += 1
                except ValueError:
                    pass
        return imported
